// Auto-generated Aksara Jawa Metadata and Unicode Map
// Generated from trained model class index
window.AKSARA_DATABASE = {
  "aksara-dasar_ba": {
    "class_name": "aksara-dasar_ba",
    "category": "aksara-dasar",
    "category_name": "Aksara Dasar (Nglegena)",
    "vowel": "a",
    "position": "Bentuk Baku",
    "base_consonant": "Ba",
    "latin": "Ba",
    "unicode_char": "ꦧ",
    "desc": "Aksara dasar Ba (vokal 'a').",
    "index": 0
  },
  "aksara-dasar_ca": {
    "class_name": "aksara-dasar_ca",
    "category": "aksara-dasar",
    "category_name": "Aksara Dasar (Nglegena)",
    "vowel": "a",
    "position": "Bentuk Baku",
    "base_consonant": "Ca",
    "latin": "Ca",
    "unicode_char": "ꦕ",
    "desc": "Aksara dasar Ca (vokal 'a').",
    "index": 1
  },
  "aksara-dasar_da": {
    "class_name": "aksara-dasar_da",
    "category": "aksara-dasar",
    "category_name": "Aksara Dasar (Nglegena)",
    "vowel": "a",
    "position": "Bentuk Baku",
    "base_consonant": "Da",
    "latin": "Da",
    "unicode_char": "ꦢ",
    "desc": "Aksara dasar Da (vokal 'a').",
    "index": 2
  },
  "aksara-dasar_dha": {
    "class_name": "aksara-dasar_dha",
    "category": "aksara-dasar",
    "category_name": "Aksara Dasar (Nglegena)",
    "vowel": "a",
    "position": "Bentuk Baku",
    "base_consonant": "Dha",
    "latin": "Dha",
    "unicode_char": "ꦝ",
    "desc": "Aksara dasar Dha (vokal 'a').",
    "index": 3
  },
  "aksara-dasar_ga": {
    "class_name": "aksara-dasar_ga",
    "category": "aksara-dasar",
    "category_name": "Aksara Dasar (Nglegena)",
    "vowel": "a",
    "position": "Bentuk Baku",
    "base_consonant": "Ga",
    "latin": "Ga",
    "unicode_char": "ꦒ",
    "desc": "Aksara dasar Ga (vokal 'a').",
    "index": 4
  },
  "aksara-dasar_ha": {
    "class_name": "aksara-dasar_ha",
    "category": "aksara-dasar",
    "category_name": "Aksara Dasar (Nglegena)",
    "vowel": "a",
    "position": "Bentuk Baku",
    "base_consonant": "Ha",
    "latin": "Ha",
    "unicode_char": "ꦲ",
    "desc": "Aksara dasar Ha (vokal 'a').",
    "index": 5
  },
  "aksara-dasar_ja": {
    "class_name": "aksara-dasar_ja",
    "category": "aksara-dasar",
    "category_name": "Aksara Dasar (Nglegena)",
    "vowel": "a",
    "position": "Bentuk Baku",
    "base_consonant": "Ja",
    "latin": "Ja",
    "unicode_char": "ꦗ",
    "desc": "Aksara dasar Ja (vokal 'a').",
    "index": 6
  },
  "aksara-dasar_ka": {
    "class_name": "aksara-dasar_ka",
    "category": "aksara-dasar",
    "category_name": "Aksara Dasar (Nglegena)",
    "vowel": "a",
    "position": "Bentuk Baku",
    "base_consonant": "Ka",
    "latin": "Ka",
    "unicode_char": "ꦏ",
    "desc": "Aksara dasar Ka (vokal 'a').",
    "index": 7
  },
  "aksara-dasar_la": {
    "class_name": "aksara-dasar_la",
    "category": "aksara-dasar",
    "category_name": "Aksara Dasar (Nglegena)",
    "vowel": "a",
    "position": "Bentuk Baku",
    "base_consonant": "La",
    "latin": "La",
    "unicode_char": "ꦭ",
    "desc": "Aksara dasar La (vokal 'a').",
    "index": 8
  },
  "aksara-dasar_ma": {
    "class_name": "aksara-dasar_ma",
    "category": "aksara-dasar",
    "category_name": "Aksara Dasar (Nglegena)",
    "vowel": "a",
    "position": "Bentuk Baku",
    "base_consonant": "Ma",
    "latin": "Ma",
    "unicode_char": "ꦩ",
    "desc": "Aksara dasar Ma (vokal 'a').",
    "index": 9
  },
  "aksara-dasar_na": {
    "class_name": "aksara-dasar_na",
    "category": "aksara-dasar",
    "category_name": "Aksara Dasar (Nglegena)",
    "vowel": "a",
    "position": "Bentuk Baku",
    "base_consonant": "Na",
    "latin": "Na",
    "unicode_char": "ꦤ",
    "desc": "Aksara dasar Na (vokal 'a').",
    "index": 10
  },
  "aksara-dasar_nga": {
    "class_name": "aksara-dasar_nga",
    "category": "aksara-dasar",
    "category_name": "Aksara Dasar (Nglegena)",
    "vowel": "a",
    "position": "Bentuk Baku",
    "base_consonant": "Nga",
    "latin": "Nga",
    "unicode_char": "ꦔ",
    "desc": "Aksara dasar Nga (vokal 'a').",
    "index": 11
  },
  "aksara-dasar_nya": {
    "class_name": "aksara-dasar_nya",
    "category": "aksara-dasar",
    "category_name": "Aksara Dasar (Nglegena)",
    "vowel": "a",
    "position": "Bentuk Baku",
    "base_consonant": "Nya",
    "latin": "Nya",
    "unicode_char": "ꦚ",
    "desc": "Aksara dasar Nya (vokal 'a').",
    "index": 12
  },
  "aksara-dasar_pa": {
    "class_name": "aksara-dasar_pa",
    "category": "aksara-dasar",
    "category_name": "Aksara Dasar (Nglegena)",
    "vowel": "a",
    "position": "Bentuk Baku",
    "base_consonant": "Pa",
    "latin": "Pa",
    "unicode_char": "ꦥ",
    "desc": "Aksara dasar Pa (vokal 'a').",
    "index": 13
  },
  "aksara-dasar_ra": {
    "class_name": "aksara-dasar_ra",
    "category": "aksara-dasar",
    "category_name": "Aksara Dasar (Nglegena)",
    "vowel": "a",
    "position": "Bentuk Baku",
    "base_consonant": "Ra",
    "latin": "Ra",
    "unicode_char": "ꦫ",
    "desc": "Aksara dasar Ra (vokal 'a').",
    "index": 14
  },
  "aksara-dasar_sa": {
    "class_name": "aksara-dasar_sa",
    "category": "aksara-dasar",
    "category_name": "Aksara Dasar (Nglegena)",
    "vowel": "a",
    "position": "Bentuk Baku",
    "base_consonant": "Sa",
    "latin": "Sa",
    "unicode_char": "ꦱ",
    "desc": "Aksara dasar Sa (vokal 'a').",
    "index": 15
  },
  "aksara-dasar_ta": {
    "class_name": "aksara-dasar_ta",
    "category": "aksara-dasar",
    "category_name": "Aksara Dasar (Nglegena)",
    "vowel": "a",
    "position": "Bentuk Baku",
    "base_consonant": "Ta",
    "latin": "Ta",
    "unicode_char": "ꦠ",
    "desc": "Aksara dasar Ta (vokal 'a').",
    "index": 16
  },
  "aksara-dasar_tha": {
    "class_name": "aksara-dasar_tha",
    "category": "aksara-dasar",
    "category_name": "Aksara Dasar (Nglegena)",
    "vowel": "a",
    "position": "Bentuk Baku",
    "base_consonant": "Tha",
    "latin": "Tha",
    "unicode_char": "ꦛ",
    "desc": "Aksara dasar Tha (vokal 'a').",
    "index": 17
  },
  "aksara-dasar_wa": {
    "class_name": "aksara-dasar_wa",
    "category": "aksara-dasar",
    "category_name": "Aksara Dasar (Nglegena)",
    "vowel": "a",
    "position": "Bentuk Baku",
    "base_consonant": "Wa",
    "latin": "Wa",
    "unicode_char": "ꦮ",
    "desc": "Aksara dasar Wa (vokal 'a').",
    "index": 18
  },
  "aksara-dasar_ya": {
    "class_name": "aksara-dasar_ya",
    "category": "aksara-dasar",
    "category_name": "Aksara Dasar (Nglegena)",
    "vowel": "a",
    "position": "Bentuk Baku",
    "base_consonant": "Ya",
    "latin": "Ya",
    "unicode_char": "ꦪ",
    "desc": "Aksara dasar Ya (vokal 'a').",
    "index": 19
  },
  "pepet_bê": {
    "class_name": "pepet_bê",
    "category": "pepet",
    "category_name": "Sandhangan Pepet",
    "vowel": "ê",
    "position": "Di atas aksara",
    "base_consonant": "Ba",
    "latin": "Bê",
    "unicode_char": "ꦧꦼ",
    "desc": "Aksara Ba diberi Sandhangan Pepet (bunyi 'ê').",
    "index": 20
  },
  "pepet_cê": {
    "class_name": "pepet_cê",
    "category": "pepet",
    "category_name": "Sandhangan Pepet",
    "vowel": "ê",
    "position": "Di atas aksara",
    "base_consonant": "Ca",
    "latin": "Cê",
    "unicode_char": "ꦕꦼ",
    "desc": "Aksara Ca diberi Sandhangan Pepet (bunyi 'ê').",
    "index": 21
  },
  "pepet_dê": {
    "class_name": "pepet_dê",
    "category": "pepet",
    "category_name": "Sandhangan Pepet",
    "vowel": "ê",
    "position": "Di atas aksara",
    "base_consonant": "Da",
    "latin": "Dê",
    "unicode_char": "ꦢꦼ",
    "desc": "Aksara Da diberi Sandhangan Pepet (bunyi 'ê').",
    "index": 22
  },
  "pepet_dhê": {
    "class_name": "pepet_dhê",
    "category": "pepet",
    "category_name": "Sandhangan Pepet",
    "vowel": "ê",
    "position": "Di atas aksara",
    "base_consonant": "Dha",
    "latin": "Dhê",
    "unicode_char": "ꦝꦼ",
    "desc": "Aksara Dha diberi Sandhangan Pepet (bunyi 'ê').",
    "index": 23
  },
  "pepet_gê": {
    "class_name": "pepet_gê",
    "category": "pepet",
    "category_name": "Sandhangan Pepet",
    "vowel": "ê",
    "position": "Di atas aksara",
    "base_consonant": "Ga",
    "latin": "Gê",
    "unicode_char": "ꦒꦼ",
    "desc": "Aksara Ga diberi Sandhangan Pepet (bunyi 'ê').",
    "index": 24
  },
  "pepet_hê": {
    "class_name": "pepet_hê",
    "category": "pepet",
    "category_name": "Sandhangan Pepet",
    "vowel": "ê",
    "position": "Di atas aksara",
    "base_consonant": "Ha",
    "latin": "Hê",
    "unicode_char": "ꦲꦼ",
    "desc": "Aksara Ha diberi Sandhangan Pepet (bunyi 'ê').",
    "index": 25
  },
  "pepet_jê": {
    "class_name": "pepet_jê",
    "category": "pepet",
    "category_name": "Sandhangan Pepet",
    "vowel": "ê",
    "position": "Di atas aksara",
    "base_consonant": "Ja",
    "latin": "Jê",
    "unicode_char": "ꦗꦼ",
    "desc": "Aksara Ja diberi Sandhangan Pepet (bunyi 'ê').",
    "index": 26
  },
  "pepet_kê": {
    "class_name": "pepet_kê",
    "category": "pepet",
    "category_name": "Sandhangan Pepet",
    "vowel": "ê",
    "position": "Di atas aksara",
    "base_consonant": "Ka",
    "latin": "Kê",
    "unicode_char": "ꦏꦼ",
    "desc": "Aksara Ka diberi Sandhangan Pepet (bunyi 'ê').",
    "index": 27
  },
  "pepet_lê": {
    "class_name": "pepet_lê",
    "category": "pepet",
    "category_name": "Sandhangan Pepet",
    "vowel": "ê",
    "position": "Di atas aksara",
    "base_consonant": "La",
    "latin": "Lê",
    "unicode_char": "ꦭꦼ",
    "desc": "Aksara La diberi Sandhangan Pepet (bunyi 'ê').",
    "index": 28
  },
  "pepet_mê": {
    "class_name": "pepet_mê",
    "category": "pepet",
    "category_name": "Sandhangan Pepet",
    "vowel": "ê",
    "position": "Di atas aksara",
    "base_consonant": "Ma",
    "latin": "Mê",
    "unicode_char": "ꦩꦼ",
    "desc": "Aksara Ma diberi Sandhangan Pepet (bunyi 'ê').",
    "index": 29
  },
  "pepet_nê": {
    "class_name": "pepet_nê",
    "category": "pepet",
    "category_name": "Sandhangan Pepet",
    "vowel": "ê",
    "position": "Di atas aksara",
    "base_consonant": "Na",
    "latin": "Nê",
    "unicode_char": "ꦤꦼ",
    "desc": "Aksara Na diberi Sandhangan Pepet (bunyi 'ê').",
    "index": 30
  },
  "pepet_ngê": {
    "class_name": "pepet_ngê",
    "category": "pepet",
    "category_name": "Sandhangan Pepet",
    "vowel": "ê",
    "position": "Di atas aksara",
    "base_consonant": "Nga",
    "latin": "Ngê",
    "unicode_char": "ꦔꦼ",
    "desc": "Aksara Nga diberi Sandhangan Pepet (bunyi 'ê').",
    "index": 31
  },
  "pepet_nyê": {
    "class_name": "pepet_nyê",
    "category": "pepet",
    "category_name": "Sandhangan Pepet",
    "vowel": "ê",
    "position": "Di atas aksara",
    "base_consonant": "Nya",
    "latin": "Nyê",
    "unicode_char": "ꦚꦼ",
    "desc": "Aksara Nya diberi Sandhangan Pepet (bunyi 'ê').",
    "index": 32
  },
  "pepet_pê": {
    "class_name": "pepet_pê",
    "category": "pepet",
    "category_name": "Sandhangan Pepet",
    "vowel": "ê",
    "position": "Di atas aksara",
    "base_consonant": "Pa",
    "latin": "Pê",
    "unicode_char": "ꦥꦼ",
    "desc": "Aksara Pa diberi Sandhangan Pepet (bunyi 'ê').",
    "index": 33
  },
  "pepet_rê": {
    "class_name": "pepet_rê",
    "category": "pepet",
    "category_name": "Sandhangan Pepet",
    "vowel": "ê",
    "position": "Di atas aksara",
    "base_consonant": "Ra",
    "latin": "Rê",
    "unicode_char": "ꦫꦼ",
    "desc": "Aksara Ra diberi Sandhangan Pepet (bunyi 'ê').",
    "index": 34
  },
  "pepet_sê": {
    "class_name": "pepet_sê",
    "category": "pepet",
    "category_name": "Sandhangan Pepet",
    "vowel": "ê",
    "position": "Di atas aksara",
    "base_consonant": "Sa",
    "latin": "Sê",
    "unicode_char": "ꦱꦼ",
    "desc": "Aksara Sa diberi Sandhangan Pepet (bunyi 'ê').",
    "index": 35
  },
  "pepet_tê": {
    "class_name": "pepet_tê",
    "category": "pepet",
    "category_name": "Sandhangan Pepet",
    "vowel": "ê",
    "position": "Di atas aksara",
    "base_consonant": "Ta",
    "latin": "Tê",
    "unicode_char": "ꦠꦼ",
    "desc": "Aksara Ta diberi Sandhangan Pepet (bunyi 'ê').",
    "index": 36
  },
  "pepet_thê": {
    "class_name": "pepet_thê",
    "category": "pepet",
    "category_name": "Sandhangan Pepet",
    "vowel": "ê",
    "position": "Di atas aksara",
    "base_consonant": "Tha",
    "latin": "Thê",
    "unicode_char": "ꦛꦼ",
    "desc": "Aksara Tha diberi Sandhangan Pepet (bunyi 'ê').",
    "index": 37
  },
  "pepet_wê": {
    "class_name": "pepet_wê",
    "category": "pepet",
    "category_name": "Sandhangan Pepet",
    "vowel": "ê",
    "position": "Di atas aksara",
    "base_consonant": "Wa",
    "latin": "Wê",
    "unicode_char": "ꦮꦼ",
    "desc": "Aksara Wa diberi Sandhangan Pepet (bunyi 'ê').",
    "index": 38
  },
  "pepet_yê": {
    "class_name": "pepet_yê",
    "category": "pepet",
    "category_name": "Sandhangan Pepet",
    "vowel": "ê",
    "position": "Di atas aksara",
    "base_consonant": "Ya",
    "latin": "Yê",
    "unicode_char": "ꦪꦼ",
    "desc": "Aksara Ya diberi Sandhangan Pepet (bunyi 'ê').",
    "index": 39
  },
  "suku_bu": {
    "class_name": "suku_bu",
    "category": "suku",
    "category_name": "Sandhangan Suku",
    "vowel": "u",
    "position": "Di bawah kanan aksara",
    "base_consonant": "Ba",
    "latin": "Bu",
    "unicode_char": "ꦧꦸ",
    "desc": "Aksara Ba diberi Sandhangan Suku (bunyi 'u').",
    "index": 40
  },
  "suku_cu": {
    "class_name": "suku_cu",
    "category": "suku",
    "category_name": "Sandhangan Suku",
    "vowel": "u",
    "position": "Di bawah kanan aksara",
    "base_consonant": "Ca",
    "latin": "Cu",
    "unicode_char": "ꦕꦸ",
    "desc": "Aksara Ca diberi Sandhangan Suku (bunyi 'u').",
    "index": 41
  },
  "suku_dhu": {
    "class_name": "suku_dhu",
    "category": "suku",
    "category_name": "Sandhangan Suku",
    "vowel": "u",
    "position": "Di bawah kanan aksara",
    "base_consonant": "Dha",
    "latin": "Dhu",
    "unicode_char": "ꦝꦸ",
    "desc": "Aksara Dha diberi Sandhangan Suku (bunyi 'u').",
    "index": 42
  },
  "suku_du": {
    "class_name": "suku_du",
    "category": "suku",
    "category_name": "Sandhangan Suku",
    "vowel": "u",
    "position": "Di bawah kanan aksara",
    "base_consonant": "Da",
    "latin": "Du",
    "unicode_char": "ꦢꦸ",
    "desc": "Aksara Da diberi Sandhangan Suku (bunyi 'u').",
    "index": 43
  },
  "suku_gu": {
    "class_name": "suku_gu",
    "category": "suku",
    "category_name": "Sandhangan Suku",
    "vowel": "u",
    "position": "Di bawah kanan aksara",
    "base_consonant": "Ga",
    "latin": "Gu",
    "unicode_char": "ꦒꦸ",
    "desc": "Aksara Ga diberi Sandhangan Suku (bunyi 'u').",
    "index": 44
  },
  "suku_hu": {
    "class_name": "suku_hu",
    "category": "suku",
    "category_name": "Sandhangan Suku",
    "vowel": "u",
    "position": "Di bawah kanan aksara",
    "base_consonant": "Ha",
    "latin": "Hu",
    "unicode_char": "ꦲꦸ",
    "desc": "Aksara Ha diberi Sandhangan Suku (bunyi 'u').",
    "index": 45
  },
  "suku_ju": {
    "class_name": "suku_ju",
    "category": "suku",
    "category_name": "Sandhangan Suku",
    "vowel": "u",
    "position": "Di bawah kanan aksara",
    "base_consonant": "Ja",
    "latin": "Ju",
    "unicode_char": "ꦗꦸ",
    "desc": "Aksara Ja diberi Sandhangan Suku (bunyi 'u').",
    "index": 46
  },
  "suku_ku": {
    "class_name": "suku_ku",
    "category": "suku",
    "category_name": "Sandhangan Suku",
    "vowel": "u",
    "position": "Di bawah kanan aksara",
    "base_consonant": "Ka",
    "latin": "Ku",
    "unicode_char": "ꦏꦸ",
    "desc": "Aksara Ka diberi Sandhangan Suku (bunyi 'u').",
    "index": 47
  },
  "suku_lu": {
    "class_name": "suku_lu",
    "category": "suku",
    "category_name": "Sandhangan Suku",
    "vowel": "u",
    "position": "Di bawah kanan aksara",
    "base_consonant": "La",
    "latin": "Lu",
    "unicode_char": "ꦭꦸ",
    "desc": "Aksara La diberi Sandhangan Suku (bunyi 'u').",
    "index": 48
  },
  "suku_mu": {
    "class_name": "suku_mu",
    "category": "suku",
    "category_name": "Sandhangan Suku",
    "vowel": "u",
    "position": "Di bawah kanan aksara",
    "base_consonant": "Ma",
    "latin": "Mu",
    "unicode_char": "ꦩꦸ",
    "desc": "Aksara Ma diberi Sandhangan Suku (bunyi 'u').",
    "index": 49
  },
  "suku_ngu": {
    "class_name": "suku_ngu",
    "category": "suku",
    "category_name": "Sandhangan Suku",
    "vowel": "u",
    "position": "Di bawah kanan aksara",
    "base_consonant": "Nga",
    "latin": "Ngu",
    "unicode_char": "ꦔꦸ",
    "desc": "Aksara Nga diberi Sandhangan Suku (bunyi 'u').",
    "index": 50
  },
  "suku_nu": {
    "class_name": "suku_nu",
    "category": "suku",
    "category_name": "Sandhangan Suku",
    "vowel": "u",
    "position": "Di bawah kanan aksara",
    "base_consonant": "Na",
    "latin": "Nu",
    "unicode_char": "ꦤꦸ",
    "desc": "Aksara Na diberi Sandhangan Suku (bunyi 'u').",
    "index": 51
  },
  "suku_nyu": {
    "class_name": "suku_nyu",
    "category": "suku",
    "category_name": "Sandhangan Suku",
    "vowel": "u",
    "position": "Di bawah kanan aksara",
    "base_consonant": "Nya",
    "latin": "Nyu",
    "unicode_char": "ꦚꦸ",
    "desc": "Aksara Nya diberi Sandhangan Suku (bunyi 'u').",
    "index": 52
  },
  "suku_pu": {
    "class_name": "suku_pu",
    "category": "suku",
    "category_name": "Sandhangan Suku",
    "vowel": "u",
    "position": "Di bawah kanan aksara",
    "base_consonant": "Pa",
    "latin": "Pu",
    "unicode_char": "ꦥꦸ",
    "desc": "Aksara Pa diberi Sandhangan Suku (bunyi 'u').",
    "index": 53
  },
  "suku_ru": {
    "class_name": "suku_ru",
    "category": "suku",
    "category_name": "Sandhangan Suku",
    "vowel": "u",
    "position": "Di bawah kanan aksara",
    "base_consonant": "Ra",
    "latin": "Ru",
    "unicode_char": "ꦫꦸ",
    "desc": "Aksara Ra diberi Sandhangan Suku (bunyi 'u').",
    "index": 54
  },
  "suku_su": {
    "class_name": "suku_su",
    "category": "suku",
    "category_name": "Sandhangan Suku",
    "vowel": "u",
    "position": "Di bawah kanan aksara",
    "base_consonant": "Sa",
    "latin": "Su",
    "unicode_char": "ꦱꦸ",
    "desc": "Aksara Sa diberi Sandhangan Suku (bunyi 'u').",
    "index": 55
  },
  "suku_thu": {
    "class_name": "suku_thu",
    "category": "suku",
    "category_name": "Sandhangan Suku",
    "vowel": "u",
    "position": "Di bawah kanan aksara",
    "base_consonant": "Tha",
    "latin": "Thu",
    "unicode_char": "ꦛꦸ",
    "desc": "Aksara Tha diberi Sandhangan Suku (bunyi 'u').",
    "index": 56
  },
  "suku_tu": {
    "class_name": "suku_tu",
    "category": "suku",
    "category_name": "Sandhangan Suku",
    "vowel": "u",
    "position": "Di bawah kanan aksara",
    "base_consonant": "Ta",
    "latin": "Tu",
    "unicode_char": "ꦠꦸ",
    "desc": "Aksara Ta diberi Sandhangan Suku (bunyi 'u').",
    "index": 57
  },
  "suku_wu": {
    "class_name": "suku_wu",
    "category": "suku",
    "category_name": "Sandhangan Suku",
    "vowel": "u",
    "position": "Di bawah kanan aksara",
    "base_consonant": "Wa",
    "latin": "Wu",
    "unicode_char": "ꦮꦸ",
    "desc": "Aksara Wa diberi Sandhangan Suku (bunyi 'u').",
    "index": 58
  },
  "suku_yu": {
    "class_name": "suku_yu",
    "category": "suku",
    "category_name": "Sandhangan Suku",
    "vowel": "u",
    "position": "Di bawah kanan aksara",
    "base_consonant": "Ya",
    "latin": "Yu",
    "unicode_char": "ꦪꦸ",
    "desc": "Aksara Ya diberi Sandhangan Suku (bunyi 'u').",
    "index": 59
  },
  "taling-tarung_bo": {
    "class_name": "taling-tarung_bo",
    "category": "taling-tarung",
    "category_name": "Sandhangan Taling-Tarung",
    "vowel": "o",
    "position": "Mengapit (depan & belakang)",
    "base_consonant": "Ba",
    "latin": "Bo",
    "unicode_char": "ꦧꦺꦴ",
    "desc": "Aksara Ba diberi Sandhangan Taling-Tarung (bunyi 'o').",
    "index": 60
  },
  "taling-tarung_co": {
    "class_name": "taling-tarung_co",
    "category": "taling-tarung",
    "category_name": "Sandhangan Taling-Tarung",
    "vowel": "o",
    "position": "Mengapit (depan & belakang)",
    "base_consonant": "Ca",
    "latin": "Co",
    "unicode_char": "ꦕꦺꦴ",
    "desc": "Aksara Ca diberi Sandhangan Taling-Tarung (bunyi 'o').",
    "index": 61
  },
  "taling-tarung_dho": {
    "class_name": "taling-tarung_dho",
    "category": "taling-tarung",
    "category_name": "Sandhangan Taling-Tarung",
    "vowel": "o",
    "position": "Mengapit (depan & belakang)",
    "base_consonant": "Dha",
    "latin": "Dho",
    "unicode_char": "ꦝꦺꦴ",
    "desc": "Aksara Dha diberi Sandhangan Taling-Tarung (bunyi 'o').",
    "index": 62
  },
  "taling-tarung_do": {
    "class_name": "taling-tarung_do",
    "category": "taling-tarung",
    "category_name": "Sandhangan Taling-Tarung",
    "vowel": "o",
    "position": "Mengapit (depan & belakang)",
    "base_consonant": "Da",
    "latin": "Do",
    "unicode_char": "ꦢꦺꦴ",
    "desc": "Aksara Da diberi Sandhangan Taling-Tarung (bunyi 'o').",
    "index": 63
  },
  "taling-tarung_go": {
    "class_name": "taling-tarung_go",
    "category": "taling-tarung",
    "category_name": "Sandhangan Taling-Tarung",
    "vowel": "o",
    "position": "Mengapit (depan & belakang)",
    "base_consonant": "Ga",
    "latin": "Go",
    "unicode_char": "ꦒꦺꦴ",
    "desc": "Aksara Ga diberi Sandhangan Taling-Tarung (bunyi 'o').",
    "index": 64
  },
  "taling-tarung_ho": {
    "class_name": "taling-tarung_ho",
    "category": "taling-tarung",
    "category_name": "Sandhangan Taling-Tarung",
    "vowel": "o",
    "position": "Mengapit (depan & belakang)",
    "base_consonant": "Ha",
    "latin": "Ho",
    "unicode_char": "ꦲꦺꦴ",
    "desc": "Aksara Ha diberi Sandhangan Taling-Tarung (bunyi 'o').",
    "index": 65
  },
  "taling-tarung_jo": {
    "class_name": "taling-tarung_jo",
    "category": "taling-tarung",
    "category_name": "Sandhangan Taling-Tarung",
    "vowel": "o",
    "position": "Mengapit (depan & belakang)",
    "base_consonant": "Ja",
    "latin": "Jo",
    "unicode_char": "ꦗꦺꦴ",
    "desc": "Aksara Ja diberi Sandhangan Taling-Tarung (bunyi 'o').",
    "index": 66
  },
  "taling-tarung_ko": {
    "class_name": "taling-tarung_ko",
    "category": "taling-tarung",
    "category_name": "Sandhangan Taling-Tarung",
    "vowel": "o",
    "position": "Mengapit (depan & belakang)",
    "base_consonant": "Ka",
    "latin": "Ko",
    "unicode_char": "ꦏꦺꦴ",
    "desc": "Aksara Ka diberi Sandhangan Taling-Tarung (bunyi 'o').",
    "index": 67
  },
  "taling-tarung_lo": {
    "class_name": "taling-tarung_lo",
    "category": "taling-tarung",
    "category_name": "Sandhangan Taling-Tarung",
    "vowel": "o",
    "position": "Mengapit (depan & belakang)",
    "base_consonant": "La",
    "latin": "Lo",
    "unicode_char": "ꦭꦺꦴ",
    "desc": "Aksara La diberi Sandhangan Taling-Tarung (bunyi 'o').",
    "index": 68
  },
  "taling-tarung_mo": {
    "class_name": "taling-tarung_mo",
    "category": "taling-tarung",
    "category_name": "Sandhangan Taling-Tarung",
    "vowel": "o",
    "position": "Mengapit (depan & belakang)",
    "base_consonant": "Ma",
    "latin": "Mo",
    "unicode_char": "ꦩꦺꦴ",
    "desc": "Aksara Ma diberi Sandhangan Taling-Tarung (bunyi 'o').",
    "index": 69
  },
  "taling-tarung_ngo": {
    "class_name": "taling-tarung_ngo",
    "category": "taling-tarung",
    "category_name": "Sandhangan Taling-Tarung",
    "vowel": "o",
    "position": "Mengapit (depan & belakang)",
    "base_consonant": "Nga",
    "latin": "Ngo",
    "unicode_char": "ꦔꦺꦴ",
    "desc": "Aksara Nga diberi Sandhangan Taling-Tarung (bunyi 'o').",
    "index": 70
  },
  "taling-tarung_no": {
    "class_name": "taling-tarung_no",
    "category": "taling-tarung",
    "category_name": "Sandhangan Taling-Tarung",
    "vowel": "o",
    "position": "Mengapit (depan & belakang)",
    "base_consonant": "Na",
    "latin": "No",
    "unicode_char": "ꦤꦺꦴ",
    "desc": "Aksara Na diberi Sandhangan Taling-Tarung (bunyi 'o').",
    "index": 71
  },
  "taling-tarung_nyo": {
    "class_name": "taling-tarung_nyo",
    "category": "taling-tarung",
    "category_name": "Sandhangan Taling-Tarung",
    "vowel": "o",
    "position": "Mengapit (depan & belakang)",
    "base_consonant": "Nya",
    "latin": "Nyo",
    "unicode_char": "ꦚꦺꦴ",
    "desc": "Aksara Nya diberi Sandhangan Taling-Tarung (bunyi 'o').",
    "index": 72
  },
  "taling-tarung_po": {
    "class_name": "taling-tarung_po",
    "category": "taling-tarung",
    "category_name": "Sandhangan Taling-Tarung",
    "vowel": "o",
    "position": "Mengapit (depan & belakang)",
    "base_consonant": "Pa",
    "latin": "Po",
    "unicode_char": "ꦥꦺꦴ",
    "desc": "Aksara Pa diberi Sandhangan Taling-Tarung (bunyi 'o').",
    "index": 73
  },
  "taling-tarung_ro": {
    "class_name": "taling-tarung_ro",
    "category": "taling-tarung",
    "category_name": "Sandhangan Taling-Tarung",
    "vowel": "o",
    "position": "Mengapit (depan & belakang)",
    "base_consonant": "Ra",
    "latin": "Ro",
    "unicode_char": "ꦫꦺꦴ",
    "desc": "Aksara Ra diberi Sandhangan Taling-Tarung (bunyi 'o').",
    "index": 74
  },
  "taling-tarung_so": {
    "class_name": "taling-tarung_so",
    "category": "taling-tarung",
    "category_name": "Sandhangan Taling-Tarung",
    "vowel": "o",
    "position": "Mengapit (depan & belakang)",
    "base_consonant": "Sa",
    "latin": "So",
    "unicode_char": "ꦱꦺꦴ",
    "desc": "Aksara Sa diberi Sandhangan Taling-Tarung (bunyi 'o').",
    "index": 75
  },
  "taling-tarung_tho": {
    "class_name": "taling-tarung_tho",
    "category": "taling-tarung",
    "category_name": "Sandhangan Taling-Tarung",
    "vowel": "o",
    "position": "Mengapit (depan & belakang)",
    "base_consonant": "Tha",
    "latin": "Tho",
    "unicode_char": "ꦛꦺꦴ",
    "desc": "Aksara Tha diberi Sandhangan Taling-Tarung (bunyi 'o').",
    "index": 76
  },
  "taling-tarung_to": {
    "class_name": "taling-tarung_to",
    "category": "taling-tarung",
    "category_name": "Sandhangan Taling-Tarung",
    "vowel": "o",
    "position": "Mengapit (depan & belakang)",
    "base_consonant": "Ta",
    "latin": "To",
    "unicode_char": "ꦠꦺꦴ",
    "desc": "Aksara Ta diberi Sandhangan Taling-Tarung (bunyi 'o').",
    "index": 77
  },
  "taling-tarung_wo": {
    "class_name": "taling-tarung_wo",
    "category": "taling-tarung",
    "category_name": "Sandhangan Taling-Tarung",
    "vowel": "o",
    "position": "Mengapit (depan & belakang)",
    "base_consonant": "Wa",
    "latin": "Wo",
    "unicode_char": "ꦮꦺꦴ",
    "desc": "Aksara Wa diberi Sandhangan Taling-Tarung (bunyi 'o').",
    "index": 78
  },
  "taling-tarung_yo": {
    "class_name": "taling-tarung_yo",
    "category": "taling-tarung",
    "category_name": "Sandhangan Taling-Tarung",
    "vowel": "o",
    "position": "Mengapit (depan & belakang)",
    "base_consonant": "Ya",
    "latin": "Yo",
    "unicode_char": "ꦪꦺꦴ",
    "desc": "Aksara Ya diberi Sandhangan Taling-Tarung (bunyi 'o').",
    "index": 79
  },
  "taling_be": {
    "class_name": "taling_be",
    "category": "taling",
    "category_name": "Sandhangan Taling",
    "vowel": "é",
    "position": "Di depan (kiri) aksara",
    "base_consonant": "Ba",
    "latin": "Bé",
    "unicode_char": "ꦧꦺ",
    "desc": "Aksara Ba diberi Sandhangan Taling (bunyi 'é').",
    "index": 80
  },
  "taling_ce": {
    "class_name": "taling_ce",
    "category": "taling",
    "category_name": "Sandhangan Taling",
    "vowel": "é",
    "position": "Di depan (kiri) aksara",
    "base_consonant": "Ca",
    "latin": "Cé",
    "unicode_char": "ꦕꦺ",
    "desc": "Aksara Ca diberi Sandhangan Taling (bunyi 'é').",
    "index": 81
  },
  "taling_de": {
    "class_name": "taling_de",
    "category": "taling",
    "category_name": "Sandhangan Taling",
    "vowel": "é",
    "position": "Di depan (kiri) aksara",
    "base_consonant": "Da",
    "latin": "Dé",
    "unicode_char": "ꦢꦺ",
    "desc": "Aksara Da diberi Sandhangan Taling (bunyi 'é').",
    "index": 82
  },
  "taling_dhe": {
    "class_name": "taling_dhe",
    "category": "taling",
    "category_name": "Sandhangan Taling",
    "vowel": "é",
    "position": "Di depan (kiri) aksara",
    "base_consonant": "Dha",
    "latin": "Dhé",
    "unicode_char": "ꦝꦺ",
    "desc": "Aksara Dha diberi Sandhangan Taling (bunyi 'é').",
    "index": 83
  },
  "taling_ge": {
    "class_name": "taling_ge",
    "category": "taling",
    "category_name": "Sandhangan Taling",
    "vowel": "é",
    "position": "Di depan (kiri) aksara",
    "base_consonant": "Ga",
    "latin": "Gé",
    "unicode_char": "ꦒꦺ",
    "desc": "Aksara Ga diberi Sandhangan Taling (bunyi 'é').",
    "index": 84
  },
  "taling_he": {
    "class_name": "taling_he",
    "category": "taling",
    "category_name": "Sandhangan Taling",
    "vowel": "é",
    "position": "Di depan (kiri) aksara",
    "base_consonant": "Ha",
    "latin": "Hé",
    "unicode_char": "ꦲꦺ",
    "desc": "Aksara Ha diberi Sandhangan Taling (bunyi 'é').",
    "index": 85
  },
  "taling_je": {
    "class_name": "taling_je",
    "category": "taling",
    "category_name": "Sandhangan Taling",
    "vowel": "é",
    "position": "Di depan (kiri) aksara",
    "base_consonant": "Ja",
    "latin": "Jé",
    "unicode_char": "ꦗꦺ",
    "desc": "Aksara Ja diberi Sandhangan Taling (bunyi 'é').",
    "index": 86
  },
  "taling_ke": {
    "class_name": "taling_ke",
    "category": "taling",
    "category_name": "Sandhangan Taling",
    "vowel": "é",
    "position": "Di depan (kiri) aksara",
    "base_consonant": "Ka",
    "latin": "Ké",
    "unicode_char": "ꦏꦺ",
    "desc": "Aksara Ka diberi Sandhangan Taling (bunyi 'é').",
    "index": 87
  },
  "taling_le": {
    "class_name": "taling_le",
    "category": "taling",
    "category_name": "Sandhangan Taling",
    "vowel": "é",
    "position": "Di depan (kiri) aksara",
    "base_consonant": "La",
    "latin": "Lé",
    "unicode_char": "ꦭꦺ",
    "desc": "Aksara La diberi Sandhangan Taling (bunyi 'é').",
    "index": 88
  },
  "taling_me": {
    "class_name": "taling_me",
    "category": "taling",
    "category_name": "Sandhangan Taling",
    "vowel": "é",
    "position": "Di depan (kiri) aksara",
    "base_consonant": "Ma",
    "latin": "Mé",
    "unicode_char": "ꦩꦺ",
    "desc": "Aksara Ma diberi Sandhangan Taling (bunyi 'é').",
    "index": 89
  },
  "taling_ne": {
    "class_name": "taling_ne",
    "category": "taling",
    "category_name": "Sandhangan Taling",
    "vowel": "é",
    "position": "Di depan (kiri) aksara",
    "base_consonant": "Na",
    "latin": "Né",
    "unicode_char": "ꦤꦺ",
    "desc": "Aksara Na diberi Sandhangan Taling (bunyi 'é').",
    "index": 90
  },
  "taling_nge": {
    "class_name": "taling_nge",
    "category": "taling",
    "category_name": "Sandhangan Taling",
    "vowel": "é",
    "position": "Di depan (kiri) aksara",
    "base_consonant": "Nga",
    "latin": "Ngé",
    "unicode_char": "ꦔꦺ",
    "desc": "Aksara Nga diberi Sandhangan Taling (bunyi 'é').",
    "index": 91
  },
  "taling_nye": {
    "class_name": "taling_nye",
    "category": "taling",
    "category_name": "Sandhangan Taling",
    "vowel": "é",
    "position": "Di depan (kiri) aksara",
    "base_consonant": "Nya",
    "latin": "Nyé",
    "unicode_char": "ꦚꦺ",
    "desc": "Aksara Nya diberi Sandhangan Taling (bunyi 'é').",
    "index": 92
  },
  "taling_pe": {
    "class_name": "taling_pe",
    "category": "taling",
    "category_name": "Sandhangan Taling",
    "vowel": "é",
    "position": "Di depan (kiri) aksara",
    "base_consonant": "Pa",
    "latin": "Pé",
    "unicode_char": "ꦥꦺ",
    "desc": "Aksara Pa diberi Sandhangan Taling (bunyi 'é').",
    "index": 93
  },
  "taling_re": {
    "class_name": "taling_re",
    "category": "taling",
    "category_name": "Sandhangan Taling",
    "vowel": "é",
    "position": "Di depan (kiri) aksara",
    "base_consonant": "Ra",
    "latin": "Ré",
    "unicode_char": "ꦫꦺ",
    "desc": "Aksara Ra diberi Sandhangan Taling (bunyi 'é').",
    "index": 94
  },
  "taling_se": {
    "class_name": "taling_se",
    "category": "taling",
    "category_name": "Sandhangan Taling",
    "vowel": "é",
    "position": "Di depan (kiri) aksara",
    "base_consonant": "Sa",
    "latin": "Sé",
    "unicode_char": "ꦱꦺ",
    "desc": "Aksara Sa diberi Sandhangan Taling (bunyi 'é').",
    "index": 95
  },
  "taling_te": {
    "class_name": "taling_te",
    "category": "taling",
    "category_name": "Sandhangan Taling",
    "vowel": "é",
    "position": "Di depan (kiri) aksara",
    "base_consonant": "Ta",
    "latin": "Té",
    "unicode_char": "ꦠꦺ",
    "desc": "Aksara Ta diberi Sandhangan Taling (bunyi 'é').",
    "index": 96
  },
  "taling_the": {
    "class_name": "taling_the",
    "category": "taling",
    "category_name": "Sandhangan Taling",
    "vowel": "é",
    "position": "Di depan (kiri) aksara",
    "base_consonant": "Tha",
    "latin": "Thé",
    "unicode_char": "ꦛꦺ",
    "desc": "Aksara Tha diberi Sandhangan Taling (bunyi 'é').",
    "index": 97
  },
  "taling_we": {
    "class_name": "taling_we",
    "category": "taling",
    "category_name": "Sandhangan Taling",
    "vowel": "é",
    "position": "Di depan (kiri) aksara",
    "base_consonant": "Wa",
    "latin": "Wé",
    "unicode_char": "ꦮꦺ",
    "desc": "Aksara Wa diberi Sandhangan Taling (bunyi 'é').",
    "index": 98
  },
  "taling_ye": {
    "class_name": "taling_ye",
    "category": "taling",
    "category_name": "Sandhangan Taling",
    "vowel": "é",
    "position": "Di depan (kiri) aksara",
    "base_consonant": "Ya",
    "latin": "Yé",
    "unicode_char": "ꦪꦺ",
    "desc": "Aksara Ya diberi Sandhangan Taling (bunyi 'é').",
    "index": 99
  },
  "wulu_bi": {
    "class_name": "wulu_bi",
    "category": "wulu",
    "category_name": "Sandhangan Wulu",
    "vowel": "i",
    "position": "Di atas aksara",
    "base_consonant": "Ba",
    "latin": "Bi",
    "unicode_char": "ꦧꦶ",
    "desc": "Aksara Ba diberi Sandhangan Wulu (bunyi 'i').",
    "index": 100
  },
  "wulu_ci": {
    "class_name": "wulu_ci",
    "category": "wulu",
    "category_name": "Sandhangan Wulu",
    "vowel": "i",
    "position": "Di atas aksara",
    "base_consonant": "Ca",
    "latin": "Ci",
    "unicode_char": "ꦕꦶ",
    "desc": "Aksara Ca diberi Sandhangan Wulu (bunyi 'i').",
    "index": 101
  },
  "wulu_dhi": {
    "class_name": "wulu_dhi",
    "category": "wulu",
    "category_name": "Sandhangan Wulu",
    "vowel": "i",
    "position": "Di atas aksara",
    "base_consonant": "Dha",
    "latin": "Dhi",
    "unicode_char": "ꦝꦶ",
    "desc": "Aksara Dha diberi Sandhangan Wulu (bunyi 'i').",
    "index": 102
  },
  "wulu_di": {
    "class_name": "wulu_di",
    "category": "wulu",
    "category_name": "Sandhangan Wulu",
    "vowel": "i",
    "position": "Di atas aksara",
    "base_consonant": "Da",
    "latin": "Di",
    "unicode_char": "ꦢꦶ",
    "desc": "Aksara Da diberi Sandhangan Wulu (bunyi 'i').",
    "index": 103
  },
  "wulu_gi": {
    "class_name": "wulu_gi",
    "category": "wulu",
    "category_name": "Sandhangan Wulu",
    "vowel": "i",
    "position": "Di atas aksara",
    "base_consonant": "Ga",
    "latin": "Gi",
    "unicode_char": "ꦒꦶ",
    "desc": "Aksara Ga diberi Sandhangan Wulu (bunyi 'i').",
    "index": 104
  },
  "wulu_hi": {
    "class_name": "wulu_hi",
    "category": "wulu",
    "category_name": "Sandhangan Wulu",
    "vowel": "i",
    "position": "Di atas aksara",
    "base_consonant": "Ha",
    "latin": "Hi",
    "unicode_char": "ꦲꦶ",
    "desc": "Aksara Ha diberi Sandhangan Wulu (bunyi 'i').",
    "index": 105
  },
  "wulu_ji": {
    "class_name": "wulu_ji",
    "category": "wulu",
    "category_name": "Sandhangan Wulu",
    "vowel": "i",
    "position": "Di atas aksara",
    "base_consonant": "Ja",
    "latin": "Ji",
    "unicode_char": "ꦗꦶ",
    "desc": "Aksara Ja diberi Sandhangan Wulu (bunyi 'i').",
    "index": 106
  },
  "wulu_ki": {
    "class_name": "wulu_ki",
    "category": "wulu",
    "category_name": "Sandhangan Wulu",
    "vowel": "i",
    "position": "Di atas aksara",
    "base_consonant": "Ka",
    "latin": "Ki",
    "unicode_char": "ꦏꦶ",
    "desc": "Aksara Ka diberi Sandhangan Wulu (bunyi 'i').",
    "index": 107
  },
  "wulu_li": {
    "class_name": "wulu_li",
    "category": "wulu",
    "category_name": "Sandhangan Wulu",
    "vowel": "i",
    "position": "Di atas aksara",
    "base_consonant": "La",
    "latin": "Li",
    "unicode_char": "ꦭꦶ",
    "desc": "Aksara La diberi Sandhangan Wulu (bunyi 'i').",
    "index": 108
  },
  "wulu_mi": {
    "class_name": "wulu_mi",
    "category": "wulu",
    "category_name": "Sandhangan Wulu",
    "vowel": "i",
    "position": "Di atas aksara",
    "base_consonant": "Ma",
    "latin": "Mi",
    "unicode_char": "ꦩꦶ",
    "desc": "Aksara Ma diberi Sandhangan Wulu (bunyi 'i').",
    "index": 109
  },
  "wulu_ngi": {
    "class_name": "wulu_ngi",
    "category": "wulu",
    "category_name": "Sandhangan Wulu",
    "vowel": "i",
    "position": "Di atas aksara",
    "base_consonant": "Nga",
    "latin": "Ngi",
    "unicode_char": "ꦔꦶ",
    "desc": "Aksara Nga diberi Sandhangan Wulu (bunyi 'i').",
    "index": 110
  },
  "wulu_ni": {
    "class_name": "wulu_ni",
    "category": "wulu",
    "category_name": "Sandhangan Wulu",
    "vowel": "i",
    "position": "Di atas aksara",
    "base_consonant": "Na",
    "latin": "Ni",
    "unicode_char": "ꦤꦶ",
    "desc": "Aksara Na diberi Sandhangan Wulu (bunyi 'i').",
    "index": 111
  },
  "wulu_nyi": {
    "class_name": "wulu_nyi",
    "category": "wulu",
    "category_name": "Sandhangan Wulu",
    "vowel": "i",
    "position": "Di atas aksara",
    "base_consonant": "Nya",
    "latin": "Nyi",
    "unicode_char": "ꦚꦶ",
    "desc": "Aksara Nya diberi Sandhangan Wulu (bunyi 'i').",
    "index": 112
  },
  "wulu_pi": {
    "class_name": "wulu_pi",
    "category": "wulu",
    "category_name": "Sandhangan Wulu",
    "vowel": "i",
    "position": "Di atas aksara",
    "base_consonant": "Pa",
    "latin": "Pi",
    "unicode_char": "ꦥꦶ",
    "desc": "Aksara Pa diberi Sandhangan Wulu (bunyi 'i').",
    "index": 113
  },
  "wulu_ri": {
    "class_name": "wulu_ri",
    "category": "wulu",
    "category_name": "Sandhangan Wulu",
    "vowel": "i",
    "position": "Di atas aksara",
    "base_consonant": "Ra",
    "latin": "Ri",
    "unicode_char": "ꦫꦶ",
    "desc": "Aksara Ra diberi Sandhangan Wulu (bunyi 'i').",
    "index": 114
  },
  "wulu_si": {
    "class_name": "wulu_si",
    "category": "wulu",
    "category_name": "Sandhangan Wulu",
    "vowel": "i",
    "position": "Di atas aksara",
    "base_consonant": "Sa",
    "latin": "Si",
    "unicode_char": "ꦱꦶ",
    "desc": "Aksara Sa diberi Sandhangan Wulu (bunyi 'i').",
    "index": 115
  },
  "wulu_thi": {
    "class_name": "wulu_thi",
    "category": "wulu",
    "category_name": "Sandhangan Wulu",
    "vowel": "i",
    "position": "Di atas aksara",
    "base_consonant": "Tha",
    "latin": "Thi",
    "unicode_char": "ꦛꦶ",
    "desc": "Aksara Tha diberi Sandhangan Wulu (bunyi 'i').",
    "index": 116
  },
  "wulu_ti": {
    "class_name": "wulu_ti",
    "category": "wulu",
    "category_name": "Sandhangan Wulu",
    "vowel": "i",
    "position": "Di atas aksara",
    "base_consonant": "Ta",
    "latin": "Ti",
    "unicode_char": "ꦠꦶ",
    "desc": "Aksara Ta diberi Sandhangan Wulu (bunyi 'i').",
    "index": 117
  },
  "wulu_wi": {
    "class_name": "wulu_wi",
    "category": "wulu",
    "category_name": "Sandhangan Wulu",
    "vowel": "i",
    "position": "Di atas aksara",
    "base_consonant": "Wa",
    "latin": "Wi",
    "unicode_char": "ꦮꦶ",
    "desc": "Aksara Wa diberi Sandhangan Wulu (bunyi 'i').",
    "index": 118
  },
  "wulu_yi": {
    "class_name": "wulu_yi",
    "category": "wulu",
    "category_name": "Sandhangan Wulu",
    "vowel": "i",
    "position": "Di atas aksara",
    "base_consonant": "Ya",
    "latin": "Yi",
    "unicode_char": "ꦪꦶ",
    "desc": "Aksara Ya diberi Sandhangan Wulu (bunyi 'i').",
    "index": 119
  }
};
window.AKSARA_CATEGORIES = {
  "aksara-dasar": [
    {
      "class_name": "aksara-dasar_ba",
      "category": "aksara-dasar",
      "category_name": "Aksara Dasar (Nglegena)",
      "vowel": "a",
      "position": "Bentuk Baku",
      "base_consonant": "Ba",
      "latin": "Ba",
      "unicode_char": "ꦧ",
      "desc": "Aksara dasar Ba (vokal 'a').",
      "index": 0
    },
    {
      "class_name": "aksara-dasar_ca",
      "category": "aksara-dasar",
      "category_name": "Aksara Dasar (Nglegena)",
      "vowel": "a",
      "position": "Bentuk Baku",
      "base_consonant": "Ca",
      "latin": "Ca",
      "unicode_char": "ꦕ",
      "desc": "Aksara dasar Ca (vokal 'a').",
      "index": 1
    },
    {
      "class_name": "aksara-dasar_da",
      "category": "aksara-dasar",
      "category_name": "Aksara Dasar (Nglegena)",
      "vowel": "a",
      "position": "Bentuk Baku",
      "base_consonant": "Da",
      "latin": "Da",
      "unicode_char": "ꦢ",
      "desc": "Aksara dasar Da (vokal 'a').",
      "index": 2
    },
    {
      "class_name": "aksara-dasar_dha",
      "category": "aksara-dasar",
      "category_name": "Aksara Dasar (Nglegena)",
      "vowel": "a",
      "position": "Bentuk Baku",
      "base_consonant": "Dha",
      "latin": "Dha",
      "unicode_char": "ꦝ",
      "desc": "Aksara dasar Dha (vokal 'a').",
      "index": 3
    },
    {
      "class_name": "aksara-dasar_ga",
      "category": "aksara-dasar",
      "category_name": "Aksara Dasar (Nglegena)",
      "vowel": "a",
      "position": "Bentuk Baku",
      "base_consonant": "Ga",
      "latin": "Ga",
      "unicode_char": "ꦒ",
      "desc": "Aksara dasar Ga (vokal 'a').",
      "index": 4
    },
    {
      "class_name": "aksara-dasar_ha",
      "category": "aksara-dasar",
      "category_name": "Aksara Dasar (Nglegena)",
      "vowel": "a",
      "position": "Bentuk Baku",
      "base_consonant": "Ha",
      "latin": "Ha",
      "unicode_char": "ꦲ",
      "desc": "Aksara dasar Ha (vokal 'a').",
      "index": 5
    },
    {
      "class_name": "aksara-dasar_ja",
      "category": "aksara-dasar",
      "category_name": "Aksara Dasar (Nglegena)",
      "vowel": "a",
      "position": "Bentuk Baku",
      "base_consonant": "Ja",
      "latin": "Ja",
      "unicode_char": "ꦗ",
      "desc": "Aksara dasar Ja (vokal 'a').",
      "index": 6
    },
    {
      "class_name": "aksara-dasar_ka",
      "category": "aksara-dasar",
      "category_name": "Aksara Dasar (Nglegena)",
      "vowel": "a",
      "position": "Bentuk Baku",
      "base_consonant": "Ka",
      "latin": "Ka",
      "unicode_char": "ꦏ",
      "desc": "Aksara dasar Ka (vokal 'a').",
      "index": 7
    },
    {
      "class_name": "aksara-dasar_la",
      "category": "aksara-dasar",
      "category_name": "Aksara Dasar (Nglegena)",
      "vowel": "a",
      "position": "Bentuk Baku",
      "base_consonant": "La",
      "latin": "La",
      "unicode_char": "ꦭ",
      "desc": "Aksara dasar La (vokal 'a').",
      "index": 8
    },
    {
      "class_name": "aksara-dasar_ma",
      "category": "aksara-dasar",
      "category_name": "Aksara Dasar (Nglegena)",
      "vowel": "a",
      "position": "Bentuk Baku",
      "base_consonant": "Ma",
      "latin": "Ma",
      "unicode_char": "ꦩ",
      "desc": "Aksara dasar Ma (vokal 'a').",
      "index": 9
    },
    {
      "class_name": "aksara-dasar_na",
      "category": "aksara-dasar",
      "category_name": "Aksara Dasar (Nglegena)",
      "vowel": "a",
      "position": "Bentuk Baku",
      "base_consonant": "Na",
      "latin": "Na",
      "unicode_char": "ꦤ",
      "desc": "Aksara dasar Na (vokal 'a').",
      "index": 10
    },
    {
      "class_name": "aksara-dasar_nga",
      "category": "aksara-dasar",
      "category_name": "Aksara Dasar (Nglegena)",
      "vowel": "a",
      "position": "Bentuk Baku",
      "base_consonant": "Nga",
      "latin": "Nga",
      "unicode_char": "ꦔ",
      "desc": "Aksara dasar Nga (vokal 'a').",
      "index": 11
    },
    {
      "class_name": "aksara-dasar_nya",
      "category": "aksara-dasar",
      "category_name": "Aksara Dasar (Nglegena)",
      "vowel": "a",
      "position": "Bentuk Baku",
      "base_consonant": "Nya",
      "latin": "Nya",
      "unicode_char": "ꦚ",
      "desc": "Aksara dasar Nya (vokal 'a').",
      "index": 12
    },
    {
      "class_name": "aksara-dasar_pa",
      "category": "aksara-dasar",
      "category_name": "Aksara Dasar (Nglegena)",
      "vowel": "a",
      "position": "Bentuk Baku",
      "base_consonant": "Pa",
      "latin": "Pa",
      "unicode_char": "ꦥ",
      "desc": "Aksara dasar Pa (vokal 'a').",
      "index": 13
    },
    {
      "class_name": "aksara-dasar_ra",
      "category": "aksara-dasar",
      "category_name": "Aksara Dasar (Nglegena)",
      "vowel": "a",
      "position": "Bentuk Baku",
      "base_consonant": "Ra",
      "latin": "Ra",
      "unicode_char": "ꦫ",
      "desc": "Aksara dasar Ra (vokal 'a').",
      "index": 14
    },
    {
      "class_name": "aksara-dasar_sa",
      "category": "aksara-dasar",
      "category_name": "Aksara Dasar (Nglegena)",
      "vowel": "a",
      "position": "Bentuk Baku",
      "base_consonant": "Sa",
      "latin": "Sa",
      "unicode_char": "ꦱ",
      "desc": "Aksara dasar Sa (vokal 'a').",
      "index": 15
    },
    {
      "class_name": "aksara-dasar_ta",
      "category": "aksara-dasar",
      "category_name": "Aksara Dasar (Nglegena)",
      "vowel": "a",
      "position": "Bentuk Baku",
      "base_consonant": "Ta",
      "latin": "Ta",
      "unicode_char": "ꦠ",
      "desc": "Aksara dasar Ta (vokal 'a').",
      "index": 16
    },
    {
      "class_name": "aksara-dasar_tha",
      "category": "aksara-dasar",
      "category_name": "Aksara Dasar (Nglegena)",
      "vowel": "a",
      "position": "Bentuk Baku",
      "base_consonant": "Tha",
      "latin": "Tha",
      "unicode_char": "ꦛ",
      "desc": "Aksara dasar Tha (vokal 'a').",
      "index": 17
    },
    {
      "class_name": "aksara-dasar_wa",
      "category": "aksara-dasar",
      "category_name": "Aksara Dasar (Nglegena)",
      "vowel": "a",
      "position": "Bentuk Baku",
      "base_consonant": "Wa",
      "latin": "Wa",
      "unicode_char": "ꦮ",
      "desc": "Aksara dasar Wa (vokal 'a').",
      "index": 18
    },
    {
      "class_name": "aksara-dasar_ya",
      "category": "aksara-dasar",
      "category_name": "Aksara Dasar (Nglegena)",
      "vowel": "a",
      "position": "Bentuk Baku",
      "base_consonant": "Ya",
      "latin": "Ya",
      "unicode_char": "ꦪ",
      "desc": "Aksara dasar Ya (vokal 'a').",
      "index": 19
    }
  ],
  "pepet": [
    {
      "class_name": "pepet_bê",
      "category": "pepet",
      "category_name": "Sandhangan Pepet",
      "vowel": "ê",
      "position": "Di atas aksara",
      "base_consonant": "Ba",
      "latin": "Bê",
      "unicode_char": "ꦧꦼ",
      "desc": "Aksara Ba diberi Sandhangan Pepet (bunyi 'ê').",
      "index": 20
    },
    {
      "class_name": "pepet_cê",
      "category": "pepet",
      "category_name": "Sandhangan Pepet",
      "vowel": "ê",
      "position": "Di atas aksara",
      "base_consonant": "Ca",
      "latin": "Cê",
      "unicode_char": "ꦕꦼ",
      "desc": "Aksara Ca diberi Sandhangan Pepet (bunyi 'ê').",
      "index": 21
    },
    {
      "class_name": "pepet_dê",
      "category": "pepet",
      "category_name": "Sandhangan Pepet",
      "vowel": "ê",
      "position": "Di atas aksara",
      "base_consonant": "Da",
      "latin": "Dê",
      "unicode_char": "ꦢꦼ",
      "desc": "Aksara Da diberi Sandhangan Pepet (bunyi 'ê').",
      "index": 22
    },
    {
      "class_name": "pepet_dhê",
      "category": "pepet",
      "category_name": "Sandhangan Pepet",
      "vowel": "ê",
      "position": "Di atas aksara",
      "base_consonant": "Dha",
      "latin": "Dhê",
      "unicode_char": "ꦝꦼ",
      "desc": "Aksara Dha diberi Sandhangan Pepet (bunyi 'ê').",
      "index": 23
    },
    {
      "class_name": "pepet_gê",
      "category": "pepet",
      "category_name": "Sandhangan Pepet",
      "vowel": "ê",
      "position": "Di atas aksara",
      "base_consonant": "Ga",
      "latin": "Gê",
      "unicode_char": "ꦒꦼ",
      "desc": "Aksara Ga diberi Sandhangan Pepet (bunyi 'ê').",
      "index": 24
    },
    {
      "class_name": "pepet_hê",
      "category": "pepet",
      "category_name": "Sandhangan Pepet",
      "vowel": "ê",
      "position": "Di atas aksara",
      "base_consonant": "Ha",
      "latin": "Hê",
      "unicode_char": "ꦲꦼ",
      "desc": "Aksara Ha diberi Sandhangan Pepet (bunyi 'ê').",
      "index": 25
    },
    {
      "class_name": "pepet_jê",
      "category": "pepet",
      "category_name": "Sandhangan Pepet",
      "vowel": "ê",
      "position": "Di atas aksara",
      "base_consonant": "Ja",
      "latin": "Jê",
      "unicode_char": "ꦗꦼ",
      "desc": "Aksara Ja diberi Sandhangan Pepet (bunyi 'ê').",
      "index": 26
    },
    {
      "class_name": "pepet_kê",
      "category": "pepet",
      "category_name": "Sandhangan Pepet",
      "vowel": "ê",
      "position": "Di atas aksara",
      "base_consonant": "Ka",
      "latin": "Kê",
      "unicode_char": "ꦏꦼ",
      "desc": "Aksara Ka diberi Sandhangan Pepet (bunyi 'ê').",
      "index": 27
    },
    {
      "class_name": "pepet_lê",
      "category": "pepet",
      "category_name": "Sandhangan Pepet",
      "vowel": "ê",
      "position": "Di atas aksara",
      "base_consonant": "La",
      "latin": "Lê",
      "unicode_char": "ꦭꦼ",
      "desc": "Aksara La diberi Sandhangan Pepet (bunyi 'ê').",
      "index": 28
    },
    {
      "class_name": "pepet_mê",
      "category": "pepet",
      "category_name": "Sandhangan Pepet",
      "vowel": "ê",
      "position": "Di atas aksara",
      "base_consonant": "Ma",
      "latin": "Mê",
      "unicode_char": "ꦩꦼ",
      "desc": "Aksara Ma diberi Sandhangan Pepet (bunyi 'ê').",
      "index": 29
    },
    {
      "class_name": "pepet_nê",
      "category": "pepet",
      "category_name": "Sandhangan Pepet",
      "vowel": "ê",
      "position": "Di atas aksara",
      "base_consonant": "Na",
      "latin": "Nê",
      "unicode_char": "ꦤꦼ",
      "desc": "Aksara Na diberi Sandhangan Pepet (bunyi 'ê').",
      "index": 30
    },
    {
      "class_name": "pepet_ngê",
      "category": "pepet",
      "category_name": "Sandhangan Pepet",
      "vowel": "ê",
      "position": "Di atas aksara",
      "base_consonant": "Nga",
      "latin": "Ngê",
      "unicode_char": "ꦔꦼ",
      "desc": "Aksara Nga diberi Sandhangan Pepet (bunyi 'ê').",
      "index": 31
    },
    {
      "class_name": "pepet_nyê",
      "category": "pepet",
      "category_name": "Sandhangan Pepet",
      "vowel": "ê",
      "position": "Di atas aksara",
      "base_consonant": "Nya",
      "latin": "Nyê",
      "unicode_char": "ꦚꦼ",
      "desc": "Aksara Nya diberi Sandhangan Pepet (bunyi 'ê').",
      "index": 32
    },
    {
      "class_name": "pepet_pê",
      "category": "pepet",
      "category_name": "Sandhangan Pepet",
      "vowel": "ê",
      "position": "Di atas aksara",
      "base_consonant": "Pa",
      "latin": "Pê",
      "unicode_char": "ꦥꦼ",
      "desc": "Aksara Pa diberi Sandhangan Pepet (bunyi 'ê').",
      "index": 33
    },
    {
      "class_name": "pepet_rê",
      "category": "pepet",
      "category_name": "Sandhangan Pepet",
      "vowel": "ê",
      "position": "Di atas aksara",
      "base_consonant": "Ra",
      "latin": "Rê",
      "unicode_char": "ꦫꦼ",
      "desc": "Aksara Ra diberi Sandhangan Pepet (bunyi 'ê').",
      "index": 34
    },
    {
      "class_name": "pepet_sê",
      "category": "pepet",
      "category_name": "Sandhangan Pepet",
      "vowel": "ê",
      "position": "Di atas aksara",
      "base_consonant": "Sa",
      "latin": "Sê",
      "unicode_char": "ꦱꦼ",
      "desc": "Aksara Sa diberi Sandhangan Pepet (bunyi 'ê').",
      "index": 35
    },
    {
      "class_name": "pepet_tê",
      "category": "pepet",
      "category_name": "Sandhangan Pepet",
      "vowel": "ê",
      "position": "Di atas aksara",
      "base_consonant": "Ta",
      "latin": "Tê",
      "unicode_char": "ꦠꦼ",
      "desc": "Aksara Ta diberi Sandhangan Pepet (bunyi 'ê').",
      "index": 36
    },
    {
      "class_name": "pepet_thê",
      "category": "pepet",
      "category_name": "Sandhangan Pepet",
      "vowel": "ê",
      "position": "Di atas aksara",
      "base_consonant": "Tha",
      "latin": "Thê",
      "unicode_char": "ꦛꦼ",
      "desc": "Aksara Tha diberi Sandhangan Pepet (bunyi 'ê').",
      "index": 37
    },
    {
      "class_name": "pepet_wê",
      "category": "pepet",
      "category_name": "Sandhangan Pepet",
      "vowel": "ê",
      "position": "Di atas aksara",
      "base_consonant": "Wa",
      "latin": "Wê",
      "unicode_char": "ꦮꦼ",
      "desc": "Aksara Wa diberi Sandhangan Pepet (bunyi 'ê').",
      "index": 38
    },
    {
      "class_name": "pepet_yê",
      "category": "pepet",
      "category_name": "Sandhangan Pepet",
      "vowel": "ê",
      "position": "Di atas aksara",
      "base_consonant": "Ya",
      "latin": "Yê",
      "unicode_char": "ꦪꦼ",
      "desc": "Aksara Ya diberi Sandhangan Pepet (bunyi 'ê').",
      "index": 39
    }
  ],
  "suku": [
    {
      "class_name": "suku_bu",
      "category": "suku",
      "category_name": "Sandhangan Suku",
      "vowel": "u",
      "position": "Di bawah kanan aksara",
      "base_consonant": "Ba",
      "latin": "Bu",
      "unicode_char": "ꦧꦸ",
      "desc": "Aksara Ba diberi Sandhangan Suku (bunyi 'u').",
      "index": 40
    },
    {
      "class_name": "suku_cu",
      "category": "suku",
      "category_name": "Sandhangan Suku",
      "vowel": "u",
      "position": "Di bawah kanan aksara",
      "base_consonant": "Ca",
      "latin": "Cu",
      "unicode_char": "ꦕꦸ",
      "desc": "Aksara Ca diberi Sandhangan Suku (bunyi 'u').",
      "index": 41
    },
    {
      "class_name": "suku_dhu",
      "category": "suku",
      "category_name": "Sandhangan Suku",
      "vowel": "u",
      "position": "Di bawah kanan aksara",
      "base_consonant": "Dha",
      "latin": "Dhu",
      "unicode_char": "ꦝꦸ",
      "desc": "Aksara Dha diberi Sandhangan Suku (bunyi 'u').",
      "index": 42
    },
    {
      "class_name": "suku_du",
      "category": "suku",
      "category_name": "Sandhangan Suku",
      "vowel": "u",
      "position": "Di bawah kanan aksara",
      "base_consonant": "Da",
      "latin": "Du",
      "unicode_char": "ꦢꦸ",
      "desc": "Aksara Da diberi Sandhangan Suku (bunyi 'u').",
      "index": 43
    },
    {
      "class_name": "suku_gu",
      "category": "suku",
      "category_name": "Sandhangan Suku",
      "vowel": "u",
      "position": "Di bawah kanan aksara",
      "base_consonant": "Ga",
      "latin": "Gu",
      "unicode_char": "ꦒꦸ",
      "desc": "Aksara Ga diberi Sandhangan Suku (bunyi 'u').",
      "index": 44
    },
    {
      "class_name": "suku_hu",
      "category": "suku",
      "category_name": "Sandhangan Suku",
      "vowel": "u",
      "position": "Di bawah kanan aksara",
      "base_consonant": "Ha",
      "latin": "Hu",
      "unicode_char": "ꦲꦸ",
      "desc": "Aksara Ha diberi Sandhangan Suku (bunyi 'u').",
      "index": 45
    },
    {
      "class_name": "suku_ju",
      "category": "suku",
      "category_name": "Sandhangan Suku",
      "vowel": "u",
      "position": "Di bawah kanan aksara",
      "base_consonant": "Ja",
      "latin": "Ju",
      "unicode_char": "ꦗꦸ",
      "desc": "Aksara Ja diberi Sandhangan Suku (bunyi 'u').",
      "index": 46
    },
    {
      "class_name": "suku_ku",
      "category": "suku",
      "category_name": "Sandhangan Suku",
      "vowel": "u",
      "position": "Di bawah kanan aksara",
      "base_consonant": "Ka",
      "latin": "Ku",
      "unicode_char": "ꦏꦸ",
      "desc": "Aksara Ka diberi Sandhangan Suku (bunyi 'u').",
      "index": 47
    },
    {
      "class_name": "suku_lu",
      "category": "suku",
      "category_name": "Sandhangan Suku",
      "vowel": "u",
      "position": "Di bawah kanan aksara",
      "base_consonant": "La",
      "latin": "Lu",
      "unicode_char": "ꦭꦸ",
      "desc": "Aksara La diberi Sandhangan Suku (bunyi 'u').",
      "index": 48
    },
    {
      "class_name": "suku_mu",
      "category": "suku",
      "category_name": "Sandhangan Suku",
      "vowel": "u",
      "position": "Di bawah kanan aksara",
      "base_consonant": "Ma",
      "latin": "Mu",
      "unicode_char": "ꦩꦸ",
      "desc": "Aksara Ma diberi Sandhangan Suku (bunyi 'u').",
      "index": 49
    },
    {
      "class_name": "suku_ngu",
      "category": "suku",
      "category_name": "Sandhangan Suku",
      "vowel": "u",
      "position": "Di bawah kanan aksara",
      "base_consonant": "Nga",
      "latin": "Ngu",
      "unicode_char": "ꦔꦸ",
      "desc": "Aksara Nga diberi Sandhangan Suku (bunyi 'u').",
      "index": 50
    },
    {
      "class_name": "suku_nu",
      "category": "suku",
      "category_name": "Sandhangan Suku",
      "vowel": "u",
      "position": "Di bawah kanan aksara",
      "base_consonant": "Na",
      "latin": "Nu",
      "unicode_char": "ꦤꦸ",
      "desc": "Aksara Na diberi Sandhangan Suku (bunyi 'u').",
      "index": 51
    },
    {
      "class_name": "suku_nyu",
      "category": "suku",
      "category_name": "Sandhangan Suku",
      "vowel": "u",
      "position": "Di bawah kanan aksara",
      "base_consonant": "Nya",
      "latin": "Nyu",
      "unicode_char": "ꦚꦸ",
      "desc": "Aksara Nya diberi Sandhangan Suku (bunyi 'u').",
      "index": 52
    },
    {
      "class_name": "suku_pu",
      "category": "suku",
      "category_name": "Sandhangan Suku",
      "vowel": "u",
      "position": "Di bawah kanan aksara",
      "base_consonant": "Pa",
      "latin": "Pu",
      "unicode_char": "ꦥꦸ",
      "desc": "Aksara Pa diberi Sandhangan Suku (bunyi 'u').",
      "index": 53
    },
    {
      "class_name": "suku_ru",
      "category": "suku",
      "category_name": "Sandhangan Suku",
      "vowel": "u",
      "position": "Di bawah kanan aksara",
      "base_consonant": "Ra",
      "latin": "Ru",
      "unicode_char": "ꦫꦸ",
      "desc": "Aksara Ra diberi Sandhangan Suku (bunyi 'u').",
      "index": 54
    },
    {
      "class_name": "suku_su",
      "category": "suku",
      "category_name": "Sandhangan Suku",
      "vowel": "u",
      "position": "Di bawah kanan aksara",
      "base_consonant": "Sa",
      "latin": "Su",
      "unicode_char": "ꦱꦸ",
      "desc": "Aksara Sa diberi Sandhangan Suku (bunyi 'u').",
      "index": 55
    },
    {
      "class_name": "suku_thu",
      "category": "suku",
      "category_name": "Sandhangan Suku",
      "vowel": "u",
      "position": "Di bawah kanan aksara",
      "base_consonant": "Tha",
      "latin": "Thu",
      "unicode_char": "ꦛꦸ",
      "desc": "Aksara Tha diberi Sandhangan Suku (bunyi 'u').",
      "index": 56
    },
    {
      "class_name": "suku_tu",
      "category": "suku",
      "category_name": "Sandhangan Suku",
      "vowel": "u",
      "position": "Di bawah kanan aksara",
      "base_consonant": "Ta",
      "latin": "Tu",
      "unicode_char": "ꦠꦸ",
      "desc": "Aksara Ta diberi Sandhangan Suku (bunyi 'u').",
      "index": 57
    },
    {
      "class_name": "suku_wu",
      "category": "suku",
      "category_name": "Sandhangan Suku",
      "vowel": "u",
      "position": "Di bawah kanan aksara",
      "base_consonant": "Wa",
      "latin": "Wu",
      "unicode_char": "ꦮꦸ",
      "desc": "Aksara Wa diberi Sandhangan Suku (bunyi 'u').",
      "index": 58
    },
    {
      "class_name": "suku_yu",
      "category": "suku",
      "category_name": "Sandhangan Suku",
      "vowel": "u",
      "position": "Di bawah kanan aksara",
      "base_consonant": "Ya",
      "latin": "Yu",
      "unicode_char": "ꦪꦸ",
      "desc": "Aksara Ya diberi Sandhangan Suku (bunyi 'u').",
      "index": 59
    }
  ],
  "taling-tarung": [
    {
      "class_name": "taling-tarung_bo",
      "category": "taling-tarung",
      "category_name": "Sandhangan Taling-Tarung",
      "vowel": "o",
      "position": "Mengapit (depan & belakang)",
      "base_consonant": "Ba",
      "latin": "Bo",
      "unicode_char": "ꦧꦺꦴ",
      "desc": "Aksara Ba diberi Sandhangan Taling-Tarung (bunyi 'o').",
      "index": 60
    },
    {
      "class_name": "taling-tarung_co",
      "category": "taling-tarung",
      "category_name": "Sandhangan Taling-Tarung",
      "vowel": "o",
      "position": "Mengapit (depan & belakang)",
      "base_consonant": "Ca",
      "latin": "Co",
      "unicode_char": "ꦕꦺꦴ",
      "desc": "Aksara Ca diberi Sandhangan Taling-Tarung (bunyi 'o').",
      "index": 61
    },
    {
      "class_name": "taling-tarung_dho",
      "category": "taling-tarung",
      "category_name": "Sandhangan Taling-Tarung",
      "vowel": "o",
      "position": "Mengapit (depan & belakang)",
      "base_consonant": "Dha",
      "latin": "Dho",
      "unicode_char": "ꦝꦺꦴ",
      "desc": "Aksara Dha diberi Sandhangan Taling-Tarung (bunyi 'o').",
      "index": 62
    },
    {
      "class_name": "taling-tarung_do",
      "category": "taling-tarung",
      "category_name": "Sandhangan Taling-Tarung",
      "vowel": "o",
      "position": "Mengapit (depan & belakang)",
      "base_consonant": "Da",
      "latin": "Do",
      "unicode_char": "ꦢꦺꦴ",
      "desc": "Aksara Da diberi Sandhangan Taling-Tarung (bunyi 'o').",
      "index": 63
    },
    {
      "class_name": "taling-tarung_go",
      "category": "taling-tarung",
      "category_name": "Sandhangan Taling-Tarung",
      "vowel": "o",
      "position": "Mengapit (depan & belakang)",
      "base_consonant": "Ga",
      "latin": "Go",
      "unicode_char": "ꦒꦺꦴ",
      "desc": "Aksara Ga diberi Sandhangan Taling-Tarung (bunyi 'o').",
      "index": 64
    },
    {
      "class_name": "taling-tarung_ho",
      "category": "taling-tarung",
      "category_name": "Sandhangan Taling-Tarung",
      "vowel": "o",
      "position": "Mengapit (depan & belakang)",
      "base_consonant": "Ha",
      "latin": "Ho",
      "unicode_char": "ꦲꦺꦴ",
      "desc": "Aksara Ha diberi Sandhangan Taling-Tarung (bunyi 'o').",
      "index": 65
    },
    {
      "class_name": "taling-tarung_jo",
      "category": "taling-tarung",
      "category_name": "Sandhangan Taling-Tarung",
      "vowel": "o",
      "position": "Mengapit (depan & belakang)",
      "base_consonant": "Ja",
      "latin": "Jo",
      "unicode_char": "ꦗꦺꦴ",
      "desc": "Aksara Ja diberi Sandhangan Taling-Tarung (bunyi 'o').",
      "index": 66
    },
    {
      "class_name": "taling-tarung_ko",
      "category": "taling-tarung",
      "category_name": "Sandhangan Taling-Tarung",
      "vowel": "o",
      "position": "Mengapit (depan & belakang)",
      "base_consonant": "Ka",
      "latin": "Ko",
      "unicode_char": "ꦏꦺꦴ",
      "desc": "Aksara Ka diberi Sandhangan Taling-Tarung (bunyi 'o').",
      "index": 67
    },
    {
      "class_name": "taling-tarung_lo",
      "category": "taling-tarung",
      "category_name": "Sandhangan Taling-Tarung",
      "vowel": "o",
      "position": "Mengapit (depan & belakang)",
      "base_consonant": "La",
      "latin": "Lo",
      "unicode_char": "ꦭꦺꦴ",
      "desc": "Aksara La diberi Sandhangan Taling-Tarung (bunyi 'o').",
      "index": 68
    },
    {
      "class_name": "taling-tarung_mo",
      "category": "taling-tarung",
      "category_name": "Sandhangan Taling-Tarung",
      "vowel": "o",
      "position": "Mengapit (depan & belakang)",
      "base_consonant": "Ma",
      "latin": "Mo",
      "unicode_char": "ꦩꦺꦴ",
      "desc": "Aksara Ma diberi Sandhangan Taling-Tarung (bunyi 'o').",
      "index": 69
    },
    {
      "class_name": "taling-tarung_ngo",
      "category": "taling-tarung",
      "category_name": "Sandhangan Taling-Tarung",
      "vowel": "o",
      "position": "Mengapit (depan & belakang)",
      "base_consonant": "Nga",
      "latin": "Ngo",
      "unicode_char": "ꦔꦺꦴ",
      "desc": "Aksara Nga diberi Sandhangan Taling-Tarung (bunyi 'o').",
      "index": 70
    },
    {
      "class_name": "taling-tarung_no",
      "category": "taling-tarung",
      "category_name": "Sandhangan Taling-Tarung",
      "vowel": "o",
      "position": "Mengapit (depan & belakang)",
      "base_consonant": "Na",
      "latin": "No",
      "unicode_char": "ꦤꦺꦴ",
      "desc": "Aksara Na diberi Sandhangan Taling-Tarung (bunyi 'o').",
      "index": 71
    },
    {
      "class_name": "taling-tarung_nyo",
      "category": "taling-tarung",
      "category_name": "Sandhangan Taling-Tarung",
      "vowel": "o",
      "position": "Mengapit (depan & belakang)",
      "base_consonant": "Nya",
      "latin": "Nyo",
      "unicode_char": "ꦚꦺꦴ",
      "desc": "Aksara Nya diberi Sandhangan Taling-Tarung (bunyi 'o').",
      "index": 72
    },
    {
      "class_name": "taling-tarung_po",
      "category": "taling-tarung",
      "category_name": "Sandhangan Taling-Tarung",
      "vowel": "o",
      "position": "Mengapit (depan & belakang)",
      "base_consonant": "Pa",
      "latin": "Po",
      "unicode_char": "ꦥꦺꦴ",
      "desc": "Aksara Pa diberi Sandhangan Taling-Tarung (bunyi 'o').",
      "index": 73
    },
    {
      "class_name": "taling-tarung_ro",
      "category": "taling-tarung",
      "category_name": "Sandhangan Taling-Tarung",
      "vowel": "o",
      "position": "Mengapit (depan & belakang)",
      "base_consonant": "Ra",
      "latin": "Ro",
      "unicode_char": "ꦫꦺꦴ",
      "desc": "Aksara Ra diberi Sandhangan Taling-Tarung (bunyi 'o').",
      "index": 74
    },
    {
      "class_name": "taling-tarung_so",
      "category": "taling-tarung",
      "category_name": "Sandhangan Taling-Tarung",
      "vowel": "o",
      "position": "Mengapit (depan & belakang)",
      "base_consonant": "Sa",
      "latin": "So",
      "unicode_char": "ꦱꦺꦴ",
      "desc": "Aksara Sa diberi Sandhangan Taling-Tarung (bunyi 'o').",
      "index": 75
    },
    {
      "class_name": "taling-tarung_tho",
      "category": "taling-tarung",
      "category_name": "Sandhangan Taling-Tarung",
      "vowel": "o",
      "position": "Mengapit (depan & belakang)",
      "base_consonant": "Tha",
      "latin": "Tho",
      "unicode_char": "ꦛꦺꦴ",
      "desc": "Aksara Tha diberi Sandhangan Taling-Tarung (bunyi 'o').",
      "index": 76
    },
    {
      "class_name": "taling-tarung_to",
      "category": "taling-tarung",
      "category_name": "Sandhangan Taling-Tarung",
      "vowel": "o",
      "position": "Mengapit (depan & belakang)",
      "base_consonant": "Ta",
      "latin": "To",
      "unicode_char": "ꦠꦺꦴ",
      "desc": "Aksara Ta diberi Sandhangan Taling-Tarung (bunyi 'o').",
      "index": 77
    },
    {
      "class_name": "taling-tarung_wo",
      "category": "taling-tarung",
      "category_name": "Sandhangan Taling-Tarung",
      "vowel": "o",
      "position": "Mengapit (depan & belakang)",
      "base_consonant": "Wa",
      "latin": "Wo",
      "unicode_char": "ꦮꦺꦴ",
      "desc": "Aksara Wa diberi Sandhangan Taling-Tarung (bunyi 'o').",
      "index": 78
    },
    {
      "class_name": "taling-tarung_yo",
      "category": "taling-tarung",
      "category_name": "Sandhangan Taling-Tarung",
      "vowel": "o",
      "position": "Mengapit (depan & belakang)",
      "base_consonant": "Ya",
      "latin": "Yo",
      "unicode_char": "ꦪꦺꦴ",
      "desc": "Aksara Ya diberi Sandhangan Taling-Tarung (bunyi 'o').",
      "index": 79
    }
  ],
  "taling": [
    {
      "class_name": "taling_be",
      "category": "taling",
      "category_name": "Sandhangan Taling",
      "vowel": "é",
      "position": "Di depan (kiri) aksara",
      "base_consonant": "Ba",
      "latin": "Bé",
      "unicode_char": "ꦧꦺ",
      "desc": "Aksara Ba diberi Sandhangan Taling (bunyi 'é').",
      "index": 80
    },
    {
      "class_name": "taling_ce",
      "category": "taling",
      "category_name": "Sandhangan Taling",
      "vowel": "é",
      "position": "Di depan (kiri) aksara",
      "base_consonant": "Ca",
      "latin": "Cé",
      "unicode_char": "ꦕꦺ",
      "desc": "Aksara Ca diberi Sandhangan Taling (bunyi 'é').",
      "index": 81
    },
    {
      "class_name": "taling_de",
      "category": "taling",
      "category_name": "Sandhangan Taling",
      "vowel": "é",
      "position": "Di depan (kiri) aksara",
      "base_consonant": "Da",
      "latin": "Dé",
      "unicode_char": "ꦢꦺ",
      "desc": "Aksara Da diberi Sandhangan Taling (bunyi 'é').",
      "index": 82
    },
    {
      "class_name": "taling_dhe",
      "category": "taling",
      "category_name": "Sandhangan Taling",
      "vowel": "é",
      "position": "Di depan (kiri) aksara",
      "base_consonant": "Dha",
      "latin": "Dhé",
      "unicode_char": "ꦝꦺ",
      "desc": "Aksara Dha diberi Sandhangan Taling (bunyi 'é').",
      "index": 83
    },
    {
      "class_name": "taling_ge",
      "category": "taling",
      "category_name": "Sandhangan Taling",
      "vowel": "é",
      "position": "Di depan (kiri) aksara",
      "base_consonant": "Ga",
      "latin": "Gé",
      "unicode_char": "ꦒꦺ",
      "desc": "Aksara Ga diberi Sandhangan Taling (bunyi 'é').",
      "index": 84
    },
    {
      "class_name": "taling_he",
      "category": "taling",
      "category_name": "Sandhangan Taling",
      "vowel": "é",
      "position": "Di depan (kiri) aksara",
      "base_consonant": "Ha",
      "latin": "Hé",
      "unicode_char": "ꦲꦺ",
      "desc": "Aksara Ha diberi Sandhangan Taling (bunyi 'é').",
      "index": 85
    },
    {
      "class_name": "taling_je",
      "category": "taling",
      "category_name": "Sandhangan Taling",
      "vowel": "é",
      "position": "Di depan (kiri) aksara",
      "base_consonant": "Ja",
      "latin": "Jé",
      "unicode_char": "ꦗꦺ",
      "desc": "Aksara Ja diberi Sandhangan Taling (bunyi 'é').",
      "index": 86
    },
    {
      "class_name": "taling_ke",
      "category": "taling",
      "category_name": "Sandhangan Taling",
      "vowel": "é",
      "position": "Di depan (kiri) aksara",
      "base_consonant": "Ka",
      "latin": "Ké",
      "unicode_char": "ꦏꦺ",
      "desc": "Aksara Ka diberi Sandhangan Taling (bunyi 'é').",
      "index": 87
    },
    {
      "class_name": "taling_le",
      "category": "taling",
      "category_name": "Sandhangan Taling",
      "vowel": "é",
      "position": "Di depan (kiri) aksara",
      "base_consonant": "La",
      "latin": "Lé",
      "unicode_char": "ꦭꦺ",
      "desc": "Aksara La diberi Sandhangan Taling (bunyi 'é').",
      "index": 88
    },
    {
      "class_name": "taling_me",
      "category": "taling",
      "category_name": "Sandhangan Taling",
      "vowel": "é",
      "position": "Di depan (kiri) aksara",
      "base_consonant": "Ma",
      "latin": "Mé",
      "unicode_char": "ꦩꦺ",
      "desc": "Aksara Ma diberi Sandhangan Taling (bunyi 'é').",
      "index": 89
    },
    {
      "class_name": "taling_ne",
      "category": "taling",
      "category_name": "Sandhangan Taling",
      "vowel": "é",
      "position": "Di depan (kiri) aksara",
      "base_consonant": "Na",
      "latin": "Né",
      "unicode_char": "ꦤꦺ",
      "desc": "Aksara Na diberi Sandhangan Taling (bunyi 'é').",
      "index": 90
    },
    {
      "class_name": "taling_nge",
      "category": "taling",
      "category_name": "Sandhangan Taling",
      "vowel": "é",
      "position": "Di depan (kiri) aksara",
      "base_consonant": "Nga",
      "latin": "Ngé",
      "unicode_char": "ꦔꦺ",
      "desc": "Aksara Nga diberi Sandhangan Taling (bunyi 'é').",
      "index": 91
    },
    {
      "class_name": "taling_nye",
      "category": "taling",
      "category_name": "Sandhangan Taling",
      "vowel": "é",
      "position": "Di depan (kiri) aksara",
      "base_consonant": "Nya",
      "latin": "Nyé",
      "unicode_char": "ꦚꦺ",
      "desc": "Aksara Nya diberi Sandhangan Taling (bunyi 'é').",
      "index": 92
    },
    {
      "class_name": "taling_pe",
      "category": "taling",
      "category_name": "Sandhangan Taling",
      "vowel": "é",
      "position": "Di depan (kiri) aksara",
      "base_consonant": "Pa",
      "latin": "Pé",
      "unicode_char": "ꦥꦺ",
      "desc": "Aksara Pa diberi Sandhangan Taling (bunyi 'é').",
      "index": 93
    },
    {
      "class_name": "taling_re",
      "category": "taling",
      "category_name": "Sandhangan Taling",
      "vowel": "é",
      "position": "Di depan (kiri) aksara",
      "base_consonant": "Ra",
      "latin": "Ré",
      "unicode_char": "ꦫꦺ",
      "desc": "Aksara Ra diberi Sandhangan Taling (bunyi 'é').",
      "index": 94
    },
    {
      "class_name": "taling_se",
      "category": "taling",
      "category_name": "Sandhangan Taling",
      "vowel": "é",
      "position": "Di depan (kiri) aksara",
      "base_consonant": "Sa",
      "latin": "Sé",
      "unicode_char": "ꦱꦺ",
      "desc": "Aksara Sa diberi Sandhangan Taling (bunyi 'é').",
      "index": 95
    },
    {
      "class_name": "taling_te",
      "category": "taling",
      "category_name": "Sandhangan Taling",
      "vowel": "é",
      "position": "Di depan (kiri) aksara",
      "base_consonant": "Ta",
      "latin": "Té",
      "unicode_char": "ꦠꦺ",
      "desc": "Aksara Ta diberi Sandhangan Taling (bunyi 'é').",
      "index": 96
    },
    {
      "class_name": "taling_the",
      "category": "taling",
      "category_name": "Sandhangan Taling",
      "vowel": "é",
      "position": "Di depan (kiri) aksara",
      "base_consonant": "Tha",
      "latin": "Thé",
      "unicode_char": "ꦛꦺ",
      "desc": "Aksara Tha diberi Sandhangan Taling (bunyi 'é').",
      "index": 97
    },
    {
      "class_name": "taling_we",
      "category": "taling",
      "category_name": "Sandhangan Taling",
      "vowel": "é",
      "position": "Di depan (kiri) aksara",
      "base_consonant": "Wa",
      "latin": "Wé",
      "unicode_char": "ꦮꦺ",
      "desc": "Aksara Wa diberi Sandhangan Taling (bunyi 'é').",
      "index": 98
    },
    {
      "class_name": "taling_ye",
      "category": "taling",
      "category_name": "Sandhangan Taling",
      "vowel": "é",
      "position": "Di depan (kiri) aksara",
      "base_consonant": "Ya",
      "latin": "Yé",
      "unicode_char": "ꦪꦺ",
      "desc": "Aksara Ya diberi Sandhangan Taling (bunyi 'é').",
      "index": 99
    }
  ],
  "wulu": [
    {
      "class_name": "wulu_bi",
      "category": "wulu",
      "category_name": "Sandhangan Wulu",
      "vowel": "i",
      "position": "Di atas aksara",
      "base_consonant": "Ba",
      "latin": "Bi",
      "unicode_char": "ꦧꦶ",
      "desc": "Aksara Ba diberi Sandhangan Wulu (bunyi 'i').",
      "index": 100
    },
    {
      "class_name": "wulu_ci",
      "category": "wulu",
      "category_name": "Sandhangan Wulu",
      "vowel": "i",
      "position": "Di atas aksara",
      "base_consonant": "Ca",
      "latin": "Ci",
      "unicode_char": "ꦕꦶ",
      "desc": "Aksara Ca diberi Sandhangan Wulu (bunyi 'i').",
      "index": 101
    },
    {
      "class_name": "wulu_dhi",
      "category": "wulu",
      "category_name": "Sandhangan Wulu",
      "vowel": "i",
      "position": "Di atas aksara",
      "base_consonant": "Dha",
      "latin": "Dhi",
      "unicode_char": "ꦝꦶ",
      "desc": "Aksara Dha diberi Sandhangan Wulu (bunyi 'i').",
      "index": 102
    },
    {
      "class_name": "wulu_di",
      "category": "wulu",
      "category_name": "Sandhangan Wulu",
      "vowel": "i",
      "position": "Di atas aksara",
      "base_consonant": "Da",
      "latin": "Di",
      "unicode_char": "ꦢꦶ",
      "desc": "Aksara Da diberi Sandhangan Wulu (bunyi 'i').",
      "index": 103
    },
    {
      "class_name": "wulu_gi",
      "category": "wulu",
      "category_name": "Sandhangan Wulu",
      "vowel": "i",
      "position": "Di atas aksara",
      "base_consonant": "Ga",
      "latin": "Gi",
      "unicode_char": "ꦒꦶ",
      "desc": "Aksara Ga diberi Sandhangan Wulu (bunyi 'i').",
      "index": 104
    },
    {
      "class_name": "wulu_hi",
      "category": "wulu",
      "category_name": "Sandhangan Wulu",
      "vowel": "i",
      "position": "Di atas aksara",
      "base_consonant": "Ha",
      "latin": "Hi",
      "unicode_char": "ꦲꦶ",
      "desc": "Aksara Ha diberi Sandhangan Wulu (bunyi 'i').",
      "index": 105
    },
    {
      "class_name": "wulu_ji",
      "category": "wulu",
      "category_name": "Sandhangan Wulu",
      "vowel": "i",
      "position": "Di atas aksara",
      "base_consonant": "Ja",
      "latin": "Ji",
      "unicode_char": "ꦗꦶ",
      "desc": "Aksara Ja diberi Sandhangan Wulu (bunyi 'i').",
      "index": 106
    },
    {
      "class_name": "wulu_ki",
      "category": "wulu",
      "category_name": "Sandhangan Wulu",
      "vowel": "i",
      "position": "Di atas aksara",
      "base_consonant": "Ka",
      "latin": "Ki",
      "unicode_char": "ꦏꦶ",
      "desc": "Aksara Ka diberi Sandhangan Wulu (bunyi 'i').",
      "index": 107
    },
    {
      "class_name": "wulu_li",
      "category": "wulu",
      "category_name": "Sandhangan Wulu",
      "vowel": "i",
      "position": "Di atas aksara",
      "base_consonant": "La",
      "latin": "Li",
      "unicode_char": "ꦭꦶ",
      "desc": "Aksara La diberi Sandhangan Wulu (bunyi 'i').",
      "index": 108
    },
    {
      "class_name": "wulu_mi",
      "category": "wulu",
      "category_name": "Sandhangan Wulu",
      "vowel": "i",
      "position": "Di atas aksara",
      "base_consonant": "Ma",
      "latin": "Mi",
      "unicode_char": "ꦩꦶ",
      "desc": "Aksara Ma diberi Sandhangan Wulu (bunyi 'i').",
      "index": 109
    },
    {
      "class_name": "wulu_ngi",
      "category": "wulu",
      "category_name": "Sandhangan Wulu",
      "vowel": "i",
      "position": "Di atas aksara",
      "base_consonant": "Nga",
      "latin": "Ngi",
      "unicode_char": "ꦔꦶ",
      "desc": "Aksara Nga diberi Sandhangan Wulu (bunyi 'i').",
      "index": 110
    },
    {
      "class_name": "wulu_ni",
      "category": "wulu",
      "category_name": "Sandhangan Wulu",
      "vowel": "i",
      "position": "Di atas aksara",
      "base_consonant": "Na",
      "latin": "Ni",
      "unicode_char": "ꦤꦶ",
      "desc": "Aksara Na diberi Sandhangan Wulu (bunyi 'i').",
      "index": 111
    },
    {
      "class_name": "wulu_nyi",
      "category": "wulu",
      "category_name": "Sandhangan Wulu",
      "vowel": "i",
      "position": "Di atas aksara",
      "base_consonant": "Nya",
      "latin": "Nyi",
      "unicode_char": "ꦚꦶ",
      "desc": "Aksara Nya diberi Sandhangan Wulu (bunyi 'i').",
      "index": 112
    },
    {
      "class_name": "wulu_pi",
      "category": "wulu",
      "category_name": "Sandhangan Wulu",
      "vowel": "i",
      "position": "Di atas aksara",
      "base_consonant": "Pa",
      "latin": "Pi",
      "unicode_char": "ꦥꦶ",
      "desc": "Aksara Pa diberi Sandhangan Wulu (bunyi 'i').",
      "index": 113
    },
    {
      "class_name": "wulu_ri",
      "category": "wulu",
      "category_name": "Sandhangan Wulu",
      "vowel": "i",
      "position": "Di atas aksara",
      "base_consonant": "Ra",
      "latin": "Ri",
      "unicode_char": "ꦫꦶ",
      "desc": "Aksara Ra diberi Sandhangan Wulu (bunyi 'i').",
      "index": 114
    },
    {
      "class_name": "wulu_si",
      "category": "wulu",
      "category_name": "Sandhangan Wulu",
      "vowel": "i",
      "position": "Di atas aksara",
      "base_consonant": "Sa",
      "latin": "Si",
      "unicode_char": "ꦱꦶ",
      "desc": "Aksara Sa diberi Sandhangan Wulu (bunyi 'i').",
      "index": 115
    },
    {
      "class_name": "wulu_thi",
      "category": "wulu",
      "category_name": "Sandhangan Wulu",
      "vowel": "i",
      "position": "Di atas aksara",
      "base_consonant": "Tha",
      "latin": "Thi",
      "unicode_char": "ꦛꦶ",
      "desc": "Aksara Tha diberi Sandhangan Wulu (bunyi 'i').",
      "index": 116
    },
    {
      "class_name": "wulu_ti",
      "category": "wulu",
      "category_name": "Sandhangan Wulu",
      "vowel": "i",
      "position": "Di atas aksara",
      "base_consonant": "Ta",
      "latin": "Ti",
      "unicode_char": "ꦠꦶ",
      "desc": "Aksara Ta diberi Sandhangan Wulu (bunyi 'i').",
      "index": 117
    },
    {
      "class_name": "wulu_wi",
      "category": "wulu",
      "category_name": "Sandhangan Wulu",
      "vowel": "i",
      "position": "Di atas aksara",
      "base_consonant": "Wa",
      "latin": "Wi",
      "unicode_char": "ꦮꦶ",
      "desc": "Aksara Wa diberi Sandhangan Wulu (bunyi 'i').",
      "index": 118
    },
    {
      "class_name": "wulu_yi",
      "category": "wulu",
      "category_name": "Sandhangan Wulu",
      "vowel": "i",
      "position": "Di atas aksara",
      "base_consonant": "Ya",
      "latin": "Yi",
      "unicode_char": "ꦪꦶ",
      "desc": "Aksara Ya diberi Sandhangan Wulu (bunyi 'i').",
      "index": 119
    }
  ]
};
